### ISSUE TITLE
Support for vertical layouts

### ISSUE THREAD

**Issue by camjackson** [yearofthedan/layabout#1]
This project is awesome.

But.

I need vertical layouts for my project.

Kthx.

**Comment by yearofthedan** [comment]
I can add an optional "direction" prop to allow switching the flex-direction from column/row; default behaviour would be row as per current behaviour. 

It's probably a good idea to rename the `widths` prop in FlexLayout to something like `sizing`, since in vertical this would affect the height.

**Comment by camjackson** [comment]
Throwing out a crazy idea, not sure if it's a good one or not...

How about `FlexRow`, `FlexColumn`, `SpacedRow`, and `SpacedColumn` as components? That would be instead of `FlexLayout` and `SpacedLayout` with a direction prop.

**Comment by yearofthedan** [comment]
Nice. That's much more consistent with the goal of low config.

**Comment by yearofthedan** [comment]
Features added

**Comment by camjackson** [comment]
Awesome!
