### ISSUE TITLE
Use propTypes from new prop-types package

### ISSUE THREAD

**Issue by camjackson** [yearofthedan/layabout#4]
Package emits this warning with the latest version of React:

`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

propTypes are going to be removed from React, so you're meant to use them from this package now: https://github.com/reactjs/prop-types

Annoying, I know :/

**Comment by yearofthedan** [comment]
Fixed in 0.7.2

**Comment by camjackson** [comment]
🎉 💯
